# Generated by Django 3.2.12 on 2024-12-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.IntegerField(default=999),
        ),
    ]
